### PR TITLE
increasing the timeouts for RPC calls

### PR DESCRIPTION
**Pull request by rraub**
To allow for slower responses from the ASU directory Service

### CODE REVIEW

**Comment by rraub** [comment]
We're still having issues with the longer timeouts: 
```
Exception: ASU Degree Service Error: 8: CURL error: Operation timed out after 14000 milliseconds with 593826 out of 805213 bytes received : https://webapp4.asu.edu/programs/XmlRpcServer
```

**Comment by nathan-rollins** [comment]
After commenting on this use with Enrollment services, their Web Services Manager, Tanya Amos, just said that they have to run these queries multiple times until the call succeeds.

... sigh

**Comment by nathan-rollins** [comment]
For the time being, we might just add a large notice to the Install Instructions that the plugin may have to be deactivated and reactivated a couple times until the dropdown menus are populated correctly. (Maybe include a status message on the plugin settings that reports if activation was successful or not?)

I am think about how I might rewrite the exception handling block to alert the admin that activating the plugin is taking longer than usual and reattempt the RPC call.

**Comment by nathan-rollins** [comment]
Hmm, maybe we could create a test section or page for the plugin settings, where the shortcodes can be tested (and caching the successful results for the end users.)

**Comment by rraub** [comment]
FYI the query to the degree service happens at page load time, not plugin activation time and it caches the results when it succeeds. So you can just refresh the page with the contact form on it until it works as a work around. ⏲

**Comment by nathan-rollins** [comment]
Increasing these timeouts doesn't really help Travis. Will have to come up with a different solution.

**Pull request closed without merging**
